[package]
name = "neural_network_scratch"
version = "0.0.2"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
polars = { version = "0.45.0", features = ["lazy"] }
rand = "0.8.5"
rand_distr = "0.4.3"
serde = "1.0.215"

